### ISSUE TITLE
Unifying docker management to the docker-compose file. Idea/question.

### ISSUE THREAD

**Issue by adrianbiro** [NCommander/idn-root-zone#1]
I haven't seen the full stream yet, but it makes me wonder why you are using the handcrafted `build.sh`, `run.sh`, and `stop.sh` scripts instead of the docker-compose file. You can specify the [network](https://docs.docker.com/compose/compose-file/#networks) pretty easily there, and it would be more approachable for other people too. 
But thanks for that anyway.

**Comment by NCommander** [comment]
I wrote this in 2018-ish, and at the time, I couldn't figure out how to set a static IP for each instance via compose. I'm not actually sure you can do it now, since Compose very much wants to have flexible networking.

**Comment by adrianbiro** [comment]
I don't know for sure, but the docker-compose and docker CLI switches should be identical in these capabilities. But you are right, it is preferable to make it flexible. Thanks for the answer!
